# Generated by Django 4.2.14 on 2025-10-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagibigContributionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('employee_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('employer_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('max_employee_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_employer_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['effective_date'],
            },
        ),
        migrations.CreateModel(
            name='PhilHealthContributionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('premium_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('max_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['effective_date'],
            },
        ),
        migrations.CreateModel(
            name='SSSContributionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employer_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ec_share', models.DecimalField(decimal_places=2, default=10.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['min_salary'],
            },
        ),
        migrations.CreateModel(
            name='TaxTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_compensation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_compensation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('base_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['min_compensation'],
            },
        ),
    ]
